np_threads: 2
threads: 4

aligner:
  tool: "hisat2"
  # add full paths here
  index_hisat2: "ref/genome/hisat2_index/grch38/genome"
  index_kallisto: "genome/kallisto_index/transcriptome.idx"

counting:
  tool: "stringtie"