threads: 6

aligner:
  tool: "kallisto"
  # add full paths here
  index_hisat2: "ref/genome/hisat2_index/grch38/genome"
  index_kallisto: "ref/genome/kallisto_index/transcriptome.idx"

counting:
  tool: "kallisto"
