############################
####### Loading data #######
############################

# import necessary modules to process sample data
from scripts.sample_processing import get_sample_data

# add sample file here
samplesfile = "samples.csv"

# get sample data
samples_data = get_sample_data(samplesfile)


# make lists for needed data
sample_mrn = samples_data['sample'].unique().tolist()
lane = samples_data['lane'].unique().tolist()
read = samples_data['read'].unique().tolist()

wildcard_constraints:
    sample_mrn= '|'.join([re.escape(x) for x in sample_mrn]),
    lane= '|'.join([re.escape(x) for x in lane]),
    read= '|'.join([re.escape(x) for x in read]),


############################
####### Configuration ######
############################

# change this parameter to the path of the config file using
# set automatically by the python wrapper script

configfile: "workflow/config_new_tuxedo.yml"

tool = config['aligner']['tool']
count_tool = config['counting']['tool']


if tool == "hisat2":
    all_targets = expand("analysis/006_count/stringtie/{sample}_{lane}/{sample}_{lane}.counts",
                        sample=sample_mrn, lane=lane)
elif tool == "kallisto":
    all_targets = "results/sleuth/differential_expression_results.tsv"
else:
    raise ValueError("Unsupported aligner specified in config.yaml")


############################
######### Workflow #########
############################

rule all:
    input:
        expand("analysis/007_multiqc/{tool}/multiqc_report.html", tool=tool),
        all_targets,
        

############################
####### Include rules ######
############################

include: "rules/001_qc.smk"
include: "rules/002_trimming.smk"
include: "rules/003_posttrim_qc.smk"
include: "rules/004_alignment.smk"
include: "rules/005_assembly.smk"
include: "rules/006_quant.smk"
include: "rules/007_diffexp.smk"
include: "rules/008_multiqc.smk"

# delete samples_data.csv with python
os.remove("sample_data.csv")

